### ISSUE TITLE
Error: Failed to process position 0 does not resolve to a source location

### ISSUE THREAD

**Issue by themagickoala** [kwonoj/swc-coverage-instrument#162]
I'm using Next.js 12.2 which includes your PR for experimental SWC plugin support, so that I can capture code coverage using istanbul comments.

When I enable your plugin and run either `next build` or `jest`, I get the error shown in the title for several files. Example stack trace:

```
 FAIL  src/utils/sort-by-direction/sort-by-direction.test.ts
  ● Test suite failed to run

    failed to process position 0 does not resolve to a source location

      at Object.transformSync (node_modules/next/build/swc/index.js:268:25)
      at Object.transformSync (node_modules/next/build/swc/index.js:318:19)
      at Object.process (node_modules/next/build/swc/jest-transformer.js:56:67)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:464:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:569:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:607:25)
```

**Comment by kwonoj** [comment]
This happens when plugin fails to lookup source location with sourcemap. Needs a minimal reproducible codes to investigate.

**Comment by kwonoj** [comment]
Filed https://github.com/swc-project/swc/issues/5535 .

**Comment by kwonoj** [comment]
0.0.10 attempts to avoid panics if lookup for the location is not available. This means there'll be some inaccurate coverages for some types, notably like enum / decorators but at least it won't stop whole execution.

**Comment by themagickoala** [comment]
Thank you! I'll let you know if I have any trouble.
